name: Create BOM

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow contains a single job called "build_iBOM"
jobs:
  build:
    name: create ibom on push
    runs-on: ubuntu-20.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Update System and install sys necessities
        run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common xvfb 
          sudo apt-get install -y libsdl2-2.0-0
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Install python dependencies
        run: |
         sudo python -m pip install --upgrade pip
         sudo python -m pip install --upgrade pip setuptools wheel
         sudo python -m pip install pyinstaller
         sudo python -m pip install pillow
         sudo pip install jsonschema
         sudo python -m pip install "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.1.1-cp38-cp38-linux_x86_64.whl"
          
      - name: Clone InteractiveHtmlBom creator
        run: sudo git clone https://github.com/openscopeproject/InteractiveHtmlBom.git
          
      - name: Create ibom.html
        run: |
         ARGS="--layer-view FB --hide-silkscreen --highlight-pin1 --no-blacklist-virtual"
         JSON_PATH="*.json"
         OUTPUT_PATH="$(pwd)/docs"
         ls -l
         cd OUTPUT_PATH
         ls -l
         cat ibom.html
         cd ..
         sudo xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" python3 InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py --no-browser $ARGS $JSON_PATH --dest-dir $OUTPUT_PATH
         cd $OUTPUT_PATH
         ls -l
         cat ibom.html
         cd ..
          
#       - name: upload html
#         uses: actions/upload-artifact@v2
#         with:
#          name: docs
#          path: output


#   deploy:
#     name: host on gh pages
#     runs-on: ubuntu-20.04
#     needs: build
#     steps:
#       - uses: actions/checkout@v2
      
#       - name: Download build
#         uses: actions/download-artifact@v2
#         with:
#           name: docs

#       - name: Deploy to GitHub Pages
#         uses: JamesIves/github-pages-deploy-action@v4.2.2
#         with:
#           branch: gh-pages
#           folder: docs
#           clean: true


#       - name: download output
#         uses: actions/download-artifact@v2
#         with: 
#          name: output_bom_view_html
