name: Create BOM

on:
  push:
    branches: [ main ]

# Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow contains a single job called "build_iBOM"
jobs:
  build_iBOM:
    name: create ibom on push
    runs-on: ubuntu-20.04

    steps:
# Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        
      - name: Update System and install sys necessities
        run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common xvfb 
          sudo apt-get install -y libsdl2-2.0-0
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
          
      - name: Install python dependencies
        run: |
         python -m pip install --upgrade pip
         python -m pip install --upgrade pip setuptools wheel
         python -m pip install pyinstaller
         python -m pip install pillow
         pip install jsonschema
         python -m pip install "https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-20.04/wxPython-4.1.1-cp38-cp38-linux_x86_64.whl"
          
      - name: Clone InteractiveHtmlBom creator
        run: git clone https://github.com/openscopeproject/InteractiveHtmlBom.git
          
      - name: Create ibom.html
        run: |
          ls -l
          JSON_PATH="BOMS/ThroughHoleSegmentVersion3_v154/ThroughHoleSegmentVersion3_v154.json"
          cat "$JSON_PATH"
          ARGS="--layer-view FB"
          mkdir output
          xvfb-run --auto-servernum --server-args "-screen 0 1024x768x24" python3 InteractiveHtmlBom/InteractiveHtmlBom/generate_interactive_bom.py $ARGS $JSON_PATH $(pwd)/output
          
      
      
