# This is a basic workflow to help you get started with Actions

name: Create BOM

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # pull_request:
  # branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build_iBOM:
    name: create ibom on push
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Update System and install sys necesseties
        run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common xvfb git
      
      # Runs a single command using the runners shell
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          
      - name: Install python dependencies
        run: |
         python -m pip install --upgrade pip
         pip install wxpython jsonschema
        
      - name: Clone InteractiveHtmlBom creator
        run: git clone https://github.com/openscopeproject/InteractiveHtmlBom.git
         
      

      # Runs a set of commands using the runners shell
      #- name: Run a multi-line script
      #  run: |
      #    echo Add other actions to build,
      #    echo test, and deploy your project.
